### ISSUE TITLE
'Open' from submenu not available.

### ISSUE THREAD

**Issue by thecoraledwards** [Automattic/google-docs-add-on#102]
'Open' from submenu not available.

**Comment by georgeh** [comment]
Hi @thecoraledwards! The open menu is controlled by Google Docs, and should always be available. Are you still having this issue? If so, can you please create a screenshot of what you're seeing? You can drag an image onto the comment box to upload it.

**Comment by thecoraledwards** [comment]
Hi! The "open" option has appeared! Perhaps it just took a while to get working? 🤔 In any case, thank you!
