### ISSUE TITLE
Syntax highlighting is broken

### ISSUE THREAD

**Issue by simardcasanova** [Automattic/google-docs-add-on#114]
Hi,

I tried to use Google Docs on a technical blog where I need math and syntax highlighting. This add-on is phenomenal, and could be extremely useful for my workflow. But when I turn my Google Docs into a WordPress draft, the outputted code is a bit messed up.

For instance this

```
[code language="r"]
df1$key <- paste(df1$first_name, df1$last_name, sep="")
df2$key <- paste(df2$first_name, df2$last_name, sep="")
[/code]
```

is outputted like this

```
</p>
<p>df1$key <- paste(df1$first_name, df1$last_name, sep="")
df2$key <- paste(df2$first_name, df2$last_name, sep="")</p>
<p>
```

Syntax highlighting works though.

Maybe there exists a workaround I'm not aware of, or maybe this issue is related to some kind of bug in the add-on code?

Thank you!

**Comment by simardcasanova** [comment]
Precision: I use a WordPress.com blog.

**Comment by georgeh** [comment]
@simardcasanova Thanks for the report. That's interesting, because the add-on shouldn't be stripping shortcodes like `[code]`. Would you mind sharing a doc that has this behavior with george.hotelling@automattic.com so I can take a look?
