### ISSUE TITLE
WordPress.com add-on for Google Docs authentication error

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/google-docs-add-on#123]
Steps:
In Google Docs, click Add-ons, search for WordPress.com app.
Try to do the Individual install and it returns the error message of:
"We're sorry, we were unable to fetch authorization credentials. Please wait a bit and try again."

Customer reported #26963420-hc
Myself and another A11N were able to reproduce.

**Comment by georgeh** [comment]
Looking into this

**Comment by yonirab** [comment]
I am seeing a similar problem after using this add on for months without problems

**Comment by georgeh** [comment]
@yonirab @purupuruo I've just deployed a new version, please give it another try and let me know if it's working

**Comment by purupuruo** [comment]
今チェックしたところ、正常にインストールできWordPressにアップロードもできました！
ありがとうございます

**Comment by yonirab** [comment]
@georgeh Problem seems to have been fixed. Thank you so much!!

**Comment by tsujike** [comment]
The installation was successful. Thank you very much. But I get an error like this "Your server returned an unexpected response. This could be a misconfiguration, a bad plugin, or something may be broken. Don't panic yet though!" and can't upload.

I will reinstall WordPress elsewhere on the same server and try to install Jetpack again.
