### ISSUE TITLE
Error TypeError: element.getText is not a function

### ISSUE THREAD

**Issue by djcowan** [Automattic/google-docs-add-on#137]
Repeated error in google docs connected using google workspace account to multisite subsite. 
Multiple google authenticated accounts tried. 
Page is created - as draft - with no content
Possible related error:

Exception: Unexpected error while getting the method or property getBlob on object DocumentApp.PositionedImage

**Comment by paulgronke** [comment]
I also encountered this error and was able to avoid it by deleting a footnote that was in my google doc. Not sure if this is(as) your situation.

**Comment by djcowan** [comment]
Thanks @paulgronke 
i think our original issue was related to the availability of the correct Rest endpoint. _[*shrugs*]_
Created, connected, and integrated a fresh wordpress.com site, jetpach authenticated user and connected a personal google account - with successful results - TT3 block theme
Appreciate being reminded this project exists.
