### ISSUE TITLE
Images don't sync when not inline

### ISSUE THREAD

**Issue by ChaosExAnima** [Automattic/google-docs-add-on#26]
When putting in images, if they are set as "Wrap Text" or "Break Text" they don't correctly sync with Google Images.

To reproduce:

1. Create new Google Doc and authenticate with a site.
2. Insert an image.
3. Publish as a draft.
4. Observe image in WP.
5. In Google Docs, set image to "Wrap Text" or "Break Text" and publish draft.
6. Observe image in WP.

Expected result: Image is there and wrapped appropriately.

Current result: Image is not there.

**Comment by georgeh** [comment]
Thanks for the detailed report! I will investigate. Do you have a public doc you can share as a test case?

**Comment by ChaosExAnima** [comment]
@georgeh - Sure: https://docs.google.com/document/d/1LwQbTl9rRdnJCowQckMb77sT1J7-aachhuWMKdnSU_w/edit

Made it view only. If you need edit access, please make a copy or me know what email to give you access at.

**Comment by georgeh** [comment]
Thanks! I was able to reproduce, I'll try to figure out what's going on. Nice cat.

**Comment by ChaosExAnima** [comment]
Thank you! :)
