### ISSUE TITLE
I can't authorize outside wordpress.com

### ISSUE THREAD

**Issue by manuti** [Automattic/google-docs-add-on#28]
I have a blog on Wordpress.com and another one outside using Jetpack plugin fully working but I can't to Authorize. I can select from the combo box but after that I recive a message, is in Spanish in my case:

> Alguien puede estar tratando de engañarlo para que le de acceso a su sitio. O simplemente puede haber encontrado un error :). De cualquier manera, por favor cierre esta ventana. 
> http://myblog-URL/wp-login.php?action=jetpack_json_api_authorization&redirect_to=...

**Comment by georgeh** [comment]
Can you check to make sure that your Jetpack plugin is updated to 4.7? If it is, can you please send me the URL of the affected blog?

**Comment by BoDonkey** [comment]
Also experiencing the same problem. First time I tried with WordPress login, got "Error: Bad nounce" (I think). Second time I tried with user credentials and got:
Exception: Request failed for https://public-api.wordpress.com/rest/v1.1/sites/104138016 returned code 403. Truncated server response: {"error":"unauthorized","message":"API calls to this blog have been disabled."} (use muteHttpExceptions option to examine full response)

Jetpack is 4.7, WP is 4.7.3, site is http://www.robertmeans.net

**Comment by georgeh** [comment]
@BoDonkey - can you please make sure that the JSON API is enabled in your Jetpack settings?
<img width="784" alt="json api" src="https://cloud.githubusercontent.com/assets/128240/23718525/c419c2fe-0405-11e7-8172-b842af8cee70.png">

**Comment by BoDonkey** [comment]
So, I didn't see that option before and it was off. Now with it enabled I get the error that my site is no longer accessible or jetpack is disabled. Neither seems to be true.

**Comment by manuti** [comment]
Wordpress 4.7.3–es_ES
Jetpack 4.7
JSON API active 
My blog is [numeriza.com](https://numeriza.com/)
and continue not working.

**Comment by georgeh** [comment]
@manuti Please check the tips at https://jetpack.com/support/getting-started-with-jetpack/troubleshooting-tips/ - it appears that your `/xmlrpc.php` is not accessible (item 4 on that list)

**Comment by manuti** [comment]
Sorry but my https://numeriza.com/xmlrpc.php is OK and in one line. 
Maybe is due to the use of https always? 
Because my blog can't be reachable at http://numeriza.com/xmlrpc.php and is redirect to https. 
I'm really interested in using the Google Docs to post to my blogs because I'm only use Linux and I don't have a decent wysiwyg tool.

**Comment by manuti** [comment]
Finally working. I don't if the SSL or what is the problem or interference but I decide to **switch off all the plug-ins except the Jetpack** and ... it works. 
Thanks for this incredible job.
