### ISSUE TITLE
"Report an issue"

### ISSUE THREAD

**Issue by jobthomas** [Automattic/google-docs-add-on#29]
When opening **Add-ons > WordPress.com for Google Docs > Help > Report an issue** in the pop-up there, it links to support.wordpress.com.

![http://cld.wthms.co/7fjb/2pPALMUV](http://cld.wthms.co/7fjb/2pPALMUV+)

They can't find the docs for the addon there as that is on https://apps.wordpress.com/google-docs/, but if the link is to report an issue, I'd suggest that they either get pointed to:

* https://github.com/Automattic/google-docs-add-on/issues/new
* or: https://chrome.google.com/webstore/detail/wordpresscom-for-google-d/baibkfjlahbcogbckhjljjenalhamjbp
* or directly to: wordpress.com/help/contact

There are two other places that they end up on wordpress.com/help where I couldn't find a single doc about this:

* The bottom right question mark in the docs window: ![http://cld.wthms.co/nXDS/496eY1D1](http://cld.wthms.co/nXDS/496eY1D1+)
* The add-ons page on the webstore: ![http://cld.wthms.co/8UaO/7r60F0KQ](http://cld.wthms.co/8UaO/7r60F0KQ+)

**Comment by georgeh** [comment]
These links have been updated to be more helpful. Thanks for the issue!
