### ISSUE TITLE
Clarify initial support prompt

### ISSUE THREAD

**Issue by johngodley** [Automattic/google-docs-add-on#35]
When the add on is first installed you are shown this prompt:

<img width="355" alt="untitled_document_-_google_docs" src="https://cloud.githubusercontent.com/assets/1277682/23848171/d267f986-07cd-11e7-962c-5bafc705149a.png">

I wasn't sure where 'open' was (and missed the little arrow thing), and it was only after digging about the menus I found it in the Add On menu.

I think it's worth changing this prompt to clarify exactly what you need to do (preferably with a picture).

- Click the 'Add on' menu
- Go to WordPress.com for Google Docs
- Click 'Open' from the submenu

**Comment by georgeh** [comment]
Good stuff. Sadly it does not support images, HTML or even line-breaks:
![screen shot 2017-03-13 at 1 55 05 pm](https://cloud.githubusercontent.com/assets/128240/23868155/c6d6ef24-07f4-11e7-8a60-37884b9815ae.png)

Also we have 255 characters. What do you think about:
> To get started click the 'Add on' menu, then go to WordPress.com for Google Docs, then choose 'Open' from the submenu

It is set on deployment, so we can update it on the next release.

**Comment by johngodley** [comment]
Yeah, I prefer the sentence version you described at the end (with the WordPress.com menu in quotes too).

Also, tiny thing but can you make the 'Add on' part match the menu: 'Add-ons'

**Comment by georgeh** [comment]
Just deployed the new wording.
