### ISSUE TITLE
Is the reload button needed?

### ISSUE THREAD

**Issue by johngodley** [Automattic/google-docs-add-on#40]
With no sites you are shown this message:

<img width="296" alt="blank" src="https://cloud.githubusercontent.com/assets/1277682/23849065/e7ef2708-07d1-11e7-9333-9a43ed32fb39.png">

In my testing the reload button is not needed - the site always appears automatically anyway. If it's not needed we should remove it.

**Comment by georgeh** [comment]
It's a little vestigial - we needed it before we had figured out how to trigger an automatic reload on site-add. Now it's there just in case the automatic reload fails. 

We are probably safe to remove it, since the automatic reload seems solid, and if it does fail then closing the sidebar will fix it.

**Comment by georgeh** [comment]
I would like to get rid of the separate `needsOauth.html` file as part of #60 (React), so this could be addressed there.

I'd also like to get rid of the Authorize button. I think there's also a UX benefit to forcing people to use the "Add WordPress Site" button to add their first site. It trains them to see that button, so they are more likely to add additional sites.

I did a quick mockup of what I am thinking for when people have 0 connected sites. Ugly yellow arrow is optional, but I would like to have some kind of visual indicator of where they should be looking.

![add-on first use](https://cloud.githubusercontent.com/assets/128240/24206546/e9bd245c-0ef4-11e7-9858-1103208c7623.png)

@jasmussen can you take a stab at this?

**Comment by jasmussen** [comment]
I'll take a look!

**Comment by georgeh** [comment]
Gone in #60
