### ISSUE TITLE
When auth window closes sometimes it doesn't go back to Google

### ISSUE THREAD

**Issue by johngodley** [Automattic/google-docs-add-on#42]
I can't reproduce this properly yet, but a few times I've authorised a connection and the WP auth tab  closes and I don't end up on Google Docs.

Detailing here as WIP.

**Comment by georgeh** [comment]
The auth tab tries to close itself by calling `window.top.close()`, which works in most browsers (I think Safari is the exception). Ideally the tab behind that is Google Docs, but if you've got a few tabs open and it may not be. Could that be the cause?

**Comment by johngodley** [comment]
It could be. A few times I got distracted, came back to the auth window, clicked authorise and ended up on a random tab. I'll keep an eye out for it again.

**Comment by johngodley** [comment]
Closing this for now as I haven't been able to reproduce it since.
