### ISSUE TITLE
Google Form: "Changes May Not Be Saved" Dialogue Pop-Up

### ISSUE THREAD

**Issue by swoolz** [Automattic/google-docs-add-on#48]
User in Livechat reported today that any time she clicks away from her main page (upon which is a Google form) she gets a dialogue box 

**Steps to reproduce:**

1. Create a Google form.
2. Embed form in page or post.
3. Load the page.
4. Click any link away from the post or page where the form is embedded, or try to close the page.

**Expected:**
5. Leave the page or exit out of the page, no dialogue box.

**Actual:**
5. A dialogue box will appear, asking if you want to 'save your changes'.

<img src="https://cldup.com/W4z2rKILon-3000x3000.png">
Any page this is embedded on, be it published or embedded in an editor (I tried this in wp-admin), it creates this dialogue:

<img src="https://cldup.com/_-8AUOewjG-3000x3000.png">

Also seen here on published page:

<img src="https://cldup.com/Ppea9_anch-3000x3000.png">

If a user submits the Google form and tries to leave, there is no longer a dialogue box that appears when someone tries to leave the page.

Only an issue in Chrome and Opera. Does not create this dialogue box in Safari or Firefox. 

Reported in #3108947-t

**Comment by georgeh** [comment]
@swoolz This isn't related to the Google Docs Add-on. Sounds like a bug with Goggle Forms embedding, and it looks like [a common issue with embedding](https://productforums.google.com/forum/#!topic/docs/zQW93hxoZ_g;context-place=topicsearchin/docs/category$3Aforms%7Csort:relevance%7Cspell:false).

**Comment by swoolz** [comment]
Ah, gotcha! Thank you so much, Georgeh.
