### ISSUE TITLE
Add support for drawings

### ISSUE THREAD

**Issue by westonruter** [Automattic/google-docs-add-on#52]
When attempting to add a drawing:

![image](https://cloud.githubusercontent.com/assets/134745/23918946/25a9083a-08b2-11e7-81a2-a86aef8cb3d8.png)

It fails to get exported to WordPress, and instead shows some `INLINE_DRAWING: InlineDrawing` placeholder content. Google Docs on left, WordPress draft on right:

![image](https://cloud.githubusercontent.com/assets/134745/23918925/146016a4-08b2-11e7-9240-c5314676bc96.png)

It would be ideal if they could be exported as SVGs.

**Comment by georgeh** [comment]
Thank you for using the add-on! Unfortunately, the [InlineDrawing](https://developers.google.com/apps-script/reference/document/inline-drawing) element doesn't offer us any way to retrieve the drawing. It looks like there are a [couple](https://code.google.com/p/google-apps-script-issues/issues/detail?id=1054) [requests](https://code.google.com/p/google-apps-script-issues/issues/detail?id=3367) for Google to support them better, but nothing is available yet.

If something changes, we'll try to support them.

That said, we are removing the "INLINE_DRAWING: InlineDrawing" bit showing up for unsupported elements.

**Comment by hjchanna** [comment]
I worked but unfortunately i stopped working. May I know how to trace it?
