### ISSUE TITLE
502 Bad Gateway on connection

### ISSUE THREAD

**Issue by danjjohnson** [Automattic/google-docs-add-on#55]
User in 3110157-t is getting a 502 Bad Gateway error when attempting to connect:

![image](https://cloud.githubusercontent.com/assets/1990037/24043768/1f142b5c-0b10-11e7-9ecd-18fe301f2061.png)

**Comment by johngodley** [comment]
The error is from the web server itself and I suspect the maximum URL length has been exceeded. The only way to confirm this is to check the server error log (or ask the hosting provider to check the logs).

If it is a URL length problem then the server will need to be configured to allow longer URLs.

If not then hopefully the error log will show what the error is.

**Comment by SebastianWalt** [comment]
I have an error log but I don't know what to look for. Ca you give me a hint?

**Comment by johngodley** [comment]
@SebastianWalt it's hard to say what to look for exactly, but if you look around the time you made the request then hopefully it will be noticeable. If not then trying authenticating again and see if anything new is output to the log.

**Comment by SebastianWalt** [comment]
cool, ill try that

**Comment by SebastianWalt** [comment]
On the server log there are no logs for that particular problem. I tried it again now and there is no new log entry.

**Comment by georgeh** [comment]
A 502 suggests that Nginx is not getting a response from the PHP FastCGI service. Have you checked the PHP error logs?

**Comment by SebastianWalt** [comment]
@georgeh thanks for the suggestion. I cant reach anyone at the hosting company. So I cant check them right now.
