### ISSUE TITLE
400 error

### ISSUE THREAD

**Issue by maryannh** [Automattic/google-docs-add-on#58]
I tried to add a draft and got the following error:

{"message":"Request failed for https://public-api.wordpress.com/rest/v1.1/sites/38783427/media/new returned code 400. Truncated server response: {\"error\":\"unsupported_mime_type\",\"message\":\"File type unknown\"} (use muteHttpExceptions option to examine full response).","name":"Exception","fileName":"Code (WordPress.com for Google Docs)","lineNumber":3280,"stack":"\tat Code (WordPress.com for Google Docs):3280 (request)\n\tat Code (WordPress.com for Google Docs):3292 (post)\n\tat Code (WordPress.com for Google Docs):3344 (uploadImage)\n\tat Code (WordPress.com for Google Docs):248 (upload)\n\tat Code (WordPress.com for Google Docs):3951\n\tat Code (WordPress.com for Google Docs):3737 (renderInlineImage)\n\tat Code (WordPress.com for Google Docs):3491 (renderElement)\n\tat Code (WordPress.com for Google Docs):3476 (renderContainer)\n\tat Code (WordPress.com for Google Docs):3551 (renderParagraph)\n\tat Code (WordPress.com for Google Docs):3487 (renderElement)\n\tat Code (WordPress.com for Google Docs):3476 (renderContainer)\n\tat Code (WordPress.com for Google Docs):253 (postToWordPress)\n"}

I was using quite a few photos in a long post (13 pages in Docs including the pics).

It worked really nicely with one image so I went a bit mad!

**Comment by georgeh** [comment]
Interesting. This could happen if you have an unsupported image type. We currently support JPEG, GIF, and PNG. Do you know if there are any other image file types in the post?

If you aren't sure or think that you are only using those image formats, could you share the document  with me to help us debug?

Also, it's likely that you can figure out which image or images are causing the problem by removing them all from the document and re-adding them one-by-one.
