### ISSUE TITLE
Extended attributes

### ISSUE THREAD

**Issue by georgeh** [Automattic/google-docs-add-on#61]
I'd like to add an accordion or drawer under each site with extra fields e.g. categories, tags, custom post type, post status, and the delete site button.

This would address the a11y issue with delete site in #31 and offer a UI for the custom post types in #27 

@jasmussen can you take a stab at this based on the `add/react` branch?

**Comment by jasmussen** [comment]
So, I made a boo-boo. When I git pulled, I saw conflicts. And like the lazy slob I am, I simply nuked my local copy, and then checked out a fresh one. Which means any config files I had to make me actually test this were wiped. Sorry about that. If you have time and energy, please ping me when you get a moment and help me get set up again.

However in absence of doing this, I did a little visual refresh to the mockups, and added that accordion you asked for.

Sites collapsed:

![site collapsed](https://cloud.githubusercontent.com/assets/1204802/24287433/fe114060-1079-11e7-913c-2dd4dc877358.png)

Site expanded: 

![site expanded](https://cloud.githubusercontent.com/assets/1204802/24287437/0334fb86-107a-11e7-8b5e-d1c2a0494d53.png)

The refresh includes tuning some colors for priority (based on the new Calypso editor), tweaking some font sizes & margins, and moving the "Add WordPress Site" to a button that just sits at the end of your list, fixing https://github.com/Automattic/google-docs-add-on/issues/40#issuecomment-288442560.

Let me know your thoughts on the visuals, and as soon as I get set up, and have a moment, I'll help implement it.

**Comment by jasmussen** [comment]
Oh, and I omitted a few features from the mockup, like status, post formats, that sort of thing. Let's discuss those piece by piece.

**Comment by georgeh** [comment]
You should be able to re-create your `gapps.config.json` pretty quickly, since you already have [node-google-apps-script](https://github.com/danthareja/node-google-apps-script) set up.

1. Go to [script.google.com](https://script.google.com/) - this will create a new project (make sure it's on the right account)
2. Copy the file id from the url - e.g. in '//script.google.com/a/google.com/d/abc123-xyz098/edit?usp=drive_web' it would be `abc123-xyz098`
3. In the project's root directory run `gapps init <fileId>`

That should create the correct `gapps.config.json` and you should be able to run `npm run deploy`

**Comment by georgeh** [comment]
The mockups look great. One bit of bikeshedding: "Move to Trash" should probably be "Remove Site" so it's clear it's about the site and not the post.

If possible, I'd like to do the "Add WordPress Site" button in #60 on the `add/react` branch and then the accordion can be in a PR for this issue.

**Comment by jasmussen** [comment]
> One bit of bikeshedding: "Move to Trash" should probably be "Remove Site" so it's clear it's about the site and not the post.

Doh. Copy paste error. Of course it should. 

> If possible, I'd like to do the "Add WordPress Site" button in #60 on the add/react branch and then the accordion can be in a PR for this issue.

Sure thing. If you can just put a centered blue button below the sites, I can make it white in this PR, when I work on it, probably monday. Sound good?

**Comment by jasmussen** [comment]
@georgeh I pushed a bunch of fixes to the `add/react` branch. Please pull.

I inserted a button that can be made to toggle the visibility of basic and extended. Can you wire that up and add a classname to whether open or closed? Then I can flip the arrow so it turns on click. Also, I added a div that you can dump all the extended stuff in. Feel free to put it there and then I can polish it up.

**Comment by georgeh** [comment]
I dig the changes! I'm going to split the changes on `add/react` to have the new "Add WordPress Site" button so that can go in #60. I'll put the toggle in `add/post-options` to go in #63 along with categories, tags, and a delete button.

Is there anything else you'd like to get in #60 before we :shipit: @jasmussen ?

**Comment by jasmussen** [comment]
All that sounds good to me. Let me know once you have the toggle & site stuff in and I'll jump back in!

**Comment by georgeh** [comment]
Deployed in #63
