### ISSUE TITLE
502 Bad Gateway when connecting a blog to google docs

### ISSUE THREAD

**Issue by orjanv** [Automattic/google-docs-add-on#65]
Hi, im trying to connect my google account to wordpress, after having installed the addon:

![bilde](https://cloud.githubusercontent.com/assets/574268/24449723/8a752f2e-1478-11e7-86dc-49dbc8132f12.png)

I select the blog with jetpack installed and click approve:

![bilde](https://cloud.githubusercontent.com/assets/574268/24449761/a859c432-1478-11e7-87d8-8d0f9f6367d4.png)

I get this 502 bad gateway error:

![bilde](https://cloud.githubusercontent.com/assets/574268/24449693/750a315c-1478-11e7-8285-282ede39f28e.png)

I'm logged in just fine into the blog with the wordpress.com user:

![bilde](https://cloud.githubusercontent.com/assets/574268/24449835/e0b28800-1478-11e7-9cc1-9891403bfc78.png)

What can be wrong?

**Comment by orjanv** [comment]
Sorry for this, I just read another issue recorded with the same topic and then found that I could for nginx add a couple of parameters to the .conf-file, which allowed for longer headings. Which worked as a charm :)

![bilde](https://cloud.githubusercontent.com/assets/574268/24450064/b47d599e-1479-11e7-8715-b99c742c03ae.png)

**Comment by johngodley** [comment]
@orjanv could you post here what settings you changed in your nginx conf file? It will help us document it. Thanks!

**Comment by orjanv** [comment]
Sure @johngodley,
In the Nginx configuration file: /etc/nginx/fastcgi.conf 

I added the following two lines at the end of this file:

fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;

Then I restarted nginx: 

service nginx restart
