### ISSUE TITLE
Investigate Jetpack authentication URL length

### ISSUE THREAD

**Issue by johngodley** [Automattic/google-docs-add-on#67]
When connecting to a Jetpack site you end up with a very long URL that on some servers can overflow the maximum header size leading to a 502 server error.

See #65, and also happens on my own server. Seems to affect Nginx more, maybe due to smaller default settings.

Steps to reproduce:

1) Add a Jetpack site
2) Note the long length of the URL

Looking into this URL we have this:

```php
Array
(
    [action] => jetpack_json_api_authorization
    [redirect_to] => <REDIRECT>
    [data] => <LONG STRING>
    [token] => <TOKEN>
    [timestamp] => 1490859498
    [nonce] => <NONCE>
    [body-hash] =>
    [signature] => <SIGNATURE>
)
```

So far so good. Breaking the `redirect_to` down further we have:

```php
Array
(
    [0] => client_id=1234
    [1] => response_type=code
    [2] => redirect_uri=<URL TO GOOGLE DOCS ADD ON>
    [3] => state=<STATE>
    [4] => action=oauth2-login
    [5] => redirect_to=https://public-api.wordpress.com/oauth2/authorize/?client_id=1234
    [6] => response_type=code
    [7] => redirect_uri=<ENCODED URL TO GOOGLE DOCS ADD ON>
    [8] => state=<STATE>
    [9] => jetpack-code
    [10] => jetpack-user-id=0
    [11] => action=oauth2-login
    [12] => blog_id=<BLOGID>
    [13] => _wpnonce=<NONCE>
)
```

Note how `redirect_uri`, `state`, `action`, and `response_type` are specified twice (with the second `redirect_uri` being double encoded). Because of how PHP's `parse_str` works only the first value will be used.

The `state` variable in particular is very long and all told can add up to > 1700 bytes.

At the moment I'm not sure whether the problem is in the add-on, Jetpack, or even WordPress (.com or .org). I'll try and work through the flow. Any additional insights would be appreciated.

**Comment by johngodley** [comment]
Scratch that, I jumped to a conclusion before fully checking - there was a mistake in decoding the URL. The params are specified twice, once in the 'main' URL, and again inside the `redirect_uri`, but this is necessary.

As the state value is so long this has the effect of pushing the URL length past some servers default length.

At this point it seems to be a general issue with Jetpack authentication

**Comment by beaulebens** [comment]
Can you create an issue in the Jetpack repo for this? I think we need to address it there, as you've suggested. Any ideas on how to address it would be great as well :) Off the top of my head, I wonder if we could switch to `POST` requests to avoid some of this?

**Comment by johngodley** [comment]
Tracked here: https://github.com/Automattic/jetpack/issues/7012
