### ISSUE TITLE
Can't connect to Wordpress.com

### ISSUE THREAD

**Issue by Diartisan** [Automattic/google-docs-add-on#71]
I have an 502 Bad Gateway error from Nginx.
Why?

**Comment by johngodley** [comment]
Is your problem similar to what is reported [here](https://github.com/Automattic/google-docs-add-on/issues/65)?

If so, can you try the fix mentioned by orjanv at the bottom of that report?

**Comment by johngodley** [comment]
I'll close this for now. Hopefully the fix solved the problem but if it hasn't then please do re-open this ticket.
