### ISSUE TITLE
"Saving" goes on forever

### ISSUE THREAD

**Issue by mikemarsian** [Automattic/google-docs-add-on#72]
I've written a not-too-long post with photos. When I try to save it to Wordpress, the saving goes on forever. I let it upload for the whole night, and still it didn't finish. When I check on Wordpress, the post is empty.

Here's the post: https://docs.google.com/document/d/1VVI8A72ASGTt6VYPUVHaAFjPylnILqEfAyTHkIfZxCE/edit?usp=sharing

Any help would be appreciated.

**Comment by mikemarsian** [comment]
Update: now I see that 3 drafts were created - the one I checked and another one are empty. The third one has a complete post uploaded correctly. Before noticing this, I logged-in to Google Docs in incognito mode and clicked Saved again (but didn't wait long). 

Not sure what to make of all of this.

**Comment by georgeh** [comment]
@mikemarsian Gorgeous photos! I just tried to post that to my test site and it worked correctly for me as well.

What site did you post this to?

My first thought is that it took too long to upload and maybe the posting system silently timed out. I have a couple ideas on how to address this, but it will be tough to verify if that's the case.

**Comment by mikemarsian** [comment]
Hi George, 
thank you for the quick reply. Posted it to [my blog](http://mike.polischuk.net)

**Comment by georgeh** [comment]
I added a timeout to the save button in 6980a03 - that will at least offer some feedback in this situation. It also make sure that you don't wind up creating a bunch of drafts for the post if they don't finish uploading.

**Comment by mikemarsian** [comment]
Sounds good.

2017-04-21 14:40 GMT-05:00 George Hotelling <notifications@github.com>:
