### ISSUE TITLE
Add support for YouTube links automatic embedding

### ISSUE THREAD

**Issue by mikemarsian** [Automattic/google-docs-add-on#73]
Currently YouTube links in Google Doc remain as links, and are not embedded as they do in Wordpress editor. Would love them to be automatically embedded when uploaded from Google Doc as well.

![image](https://cloud.githubusercontent.com/assets/184810/24916367/8b682b1c-1e9f-11e7-9900-91225577e688.png)

**Comment by georgeh** [comment]
Google Docs adds a link on URLs, which upset's WordPress's embed detection. I'll see if I can figure out a way to trigger embeds even when they have been auto-linked by Google Docs. As a work-around, you can remove the link and it will embed:

![screen shot 2017-04-11 at 11 19 36 am](https://cloud.githubusercontent.com/assets/128240/24916869/6e5a5266-1ea9-11e7-8f20-96b44fa800d3.png)

Thanks for reporting these issues!

**Comment by mikemarsian** [comment]
OK, thanks for the clarification.
