### ISSUE TITLE
Can Not Add Website

### ISSUE THREAD

**Issue by amyunus** [Automattic/google-docs-add-on#75]
Hi, I can not add my wordpress.com website (it was self hosted and using jetpack). Thanks.

<img width="521" alt="screen shot 2017-04-24 at 11 38 00" src="https://cloud.githubusercontent.com/assets/729738/25322638/e59d8756-28e2-11e7-8d5a-35edc302f34d.png">

**Comment by georgeh** [comment]
@amyunus It appears that your site URL has changed but Jetpack has not been updated. Jetpack is trying to talk to http://www.amyunus.com/wordpress/xmlrpc.php but your site's connection to Jetpack is now at https://amyunus.com/xmlrpc.php

Please [contact Jetpack support](https://jetpack.me/contact-support/) and let them know that your site's URL changed. They will be able to update it and that should fix the issue.
