### ISSUE TITLE
Content with an image included does not get saved to the draft post

### ISSUE THREAD

**Issue by designsimply** [Automattic/google-docs-add-on#80]
Steps to reproduce:

1. Install https://chrome.google.com/webstore/detail/wordpresscom-for-google-d/baibkfjlahbcogbckhjljjenalhamjbp on Chrome.
1. Start a new Google Doc.
1. When prompted for permission to run, click the "Continue" button.
1. Choose a WordPress.com account.
1. Click the "Allow" button to allow WordPress.com for Google Docs permission.
1. Add a line of text and an image.
1. Go to Add-ons > WordPress.com for Google Docs > Open.
1. Click the "Add a WordPress Site" button in the sidebar on the right.
1. Make sure you are signed in as the correct user and click the "Approve" button.
1. Add a tag and select a category in the sidebar.
1. Click the "Save" button in the sidebar on the right.
1. Note the very large error message that appears.
1. Check the post on the WordPress.com site to see if any content was saved in a draft there.

<strong>Result:</strong> the category and tag were saved but the line of text and image from the content were not saved and the following error appeared in Google Docs after clicking the Save button:

> {"message":"Cannot call method \"split\" of null.","name":"TypeError","fileName":"Code (WordPress.com for Google Docs)","lineNumber":3388,"stack":"\tat Code (WordPress.com for Google Docs):3388 (hasImageFileExtension)\n\tat Code (WordPress.com for Google Docs):3409 (uploadImage)\n\tat Code (WordPress.com for Google Docs):305 (upload)\n\tat Code (WordPress.com for Google Docs):4095\n\tat Code (WordPress.com for Google Docs):3890 (renderInlineImage)\n\tat Code (WordPress.com for Google Docs):3543 (renderElement)\n\tat Code (WordPress.com for Google Docs):3525 (renderContainer)\n\tat Code (WordPress.com for Google Docs):3656 (renderParagraph)\n\tat Code (WordPress.com for Google Docs):3539 (renderElement)\n\tat Code (WordPress.com for Google Docs):3525 (renderContainer)\n\tat Code (WordPress.com for Google Docs):310 (postToWordPress)\n"}

![screen shot 2017-06-07 at wed jun 7 7 07 41 pm](https://user-images.githubusercontent.com/1119271/26908211-6444ec2a-4bb6-11e7-8374-e6b7ef394ae8.png)
<sup>Seen at https://docs.google.com/document/d/1lIw2253r6VSosUAEClDlh-WjwkkSx38zLQASpdPE0DE/edit using Chrome 58.0.3029.110 on Mac OS X 10.12.5.</sup>

![screen shot 2017-06-07 at wed jun 7 7 12 04 pm](https://user-images.githubusercontent.com/1119271/26908277-e18e415e-4bb6-11e7-928d-be415bdc6b32.png)
<sup>Seen at https://wordpress.com/post/design5279.wordpress.com/11119 using Chrome 58.0.3029.110 on Mac OS X 10.12.5 logged in as design5279.</sup>

/hat tip @bissy for the original report at https://github.com/Automattic/wp-desktop/issues/304, thank you!

**Comment by akshansh1998** [comment]
I Got Same Issue and I am Damn Sure it is Because of Images in the Document...

@automattic Team Please fix this Problem..
