### ISSUE TITLE
Site selector has no option to search for a site

### ISSUE THREAD

**Issue by designsimply** [Automattic/google-docs-add-on#87]
Before testing you will need:

* A WordPress.com account with mulitple blogs (to trigger a site selector when connecting).
* A Google account for creating Google Docs.

Steps to reproduce:

1. Install https://chrome.google.com/webstore/detail/wordpresscom-for-google-d/baibkfjlahbcogbckhjljjenalhamjbp on Chrome.
1. Start a new Google Doc.
1. When prompted for permission to run, try to search for a site using the site selector.

<strong>Result:</strong> the site selector has no option to search for a site, and it’s apparently in random order.

![screen shot 2017-07-11 at 11 27 09](https://user-images.githubusercontent.com/1119271/28228387-88e7b344-689b-11e7-97b4-c2409fd12152.png)

/hat tip @koke for the original report at p1499765367374268-slack-dotcom

/noting some Slack conversation for reference from p1500058060275087-slack-dotcom

> the _best_ fix [would be] to convert that whole UI over to using calypso, so that we could use the calypso site picker

**Comment by georgeh** [comment]
Sorry for the delay, I missed this in my vacation catch-up. I agree that the site-selector should have a search, but per that Slack conversation that is an WPCOM API change. I'm going to close this in favor of creating a ticket in the API team's repo.
