### ISSUE TITLE
Can't add wordpress site

### ISSUE THREAD

**Issue by LobsterDM** [Automattic/google-docs-add-on#94]
Hi,
I'm trying to connect my Jetpack linked site to my Google Docs so going through the option to Add WordPress site which seems to work to the point that my WordPress website opens and then nothing happens.

My site is self hosted so could that be the issue?

Hope someone can help
Russell

**Comment by georgeh** [comment]
Hi Russell!

What should be happening is that, after you choose your website from the list, you will be asked to log into your self-hosted site. When you do, you should be redirected a couple times, then the tab should close itself, taking you back to Google Docs with your site now showing in the sidebar.

It sounds like something isn't working there, can you please [contact Jetpack support](https://jetpack.com/contact-support/) to get help troubleshooting your site?
