### ISSUE TITLE
Trying, trying and trying some more... Never works.

### ISSUE THREAD

**Issue by BlameDutchie** [Automattic/google-docs-add-on#98]
I follow the instructions, I log on with the account I use for the Wordpress.com / Jetpack domain and keep getting:

"Someone may be trying to trick you into giving them access to your site. Or it could be you just encountered a bug :). Either way, please close this window."

That comment alone, makes me wonder how serious automattic is taking the people that do not pay for Wordpress and are self-hosters... Google Addon will be deleted, I'm done with it, I'll stick to logging on to the site and use the default WP editor. Who needs a flawlessly working WP/Google connection anyway?

**Comment by georgeh** [comment]
Hi @BlameDutchie, that error occurs when the connection between the WordPress.com API and a self-hosted WordPress.org site can't be verified. 

If you decide to give the plugin another try in the future, please take a look at [these troubleshooting steps](https://apps.wordpress.com/support/#faq-googledocs-7) and re-open this ticket if they don't fix the issue.

**Comment by BlameDutchie** [comment]
Hi @georgeh , thanks for your reply.

It appears to be a double encoding issue, so I have asked my host to look into it.
Cheers.
